<?php

/** @var $_apiHelper Minkasu_Wallet_Helper_Api */
$_apiHelper = Mage::helper('minkasu_wallet/api');
$_apiEstimateEnabled = $_apiHelper->isApiEstimateEnabled();

$show_minkasu_estimate_box = $_apiEstimateEnabled;

?>


<?php if ($show_minkasu_estimate_box) : ?>

<div id="mk_shipping_est_div" style="display: block; overflow: auto"> 
    <table style="border: 0px; margin:0px"><tr>
	<!--td style="border: 0px; padding: 0px; width:100%"></td --> 
        <td style="border: 0px; padding: 0px; padding-bottom: 30px; padding-top: 20px;"> 

    <table id="mk_shipping_est_table" style="background-color: #E7F6F0; border: 1px solid #19D383; border-collapse: separate; border-spacing: 0px; border-radius: 3px; margin: 0px; padding-bottom: 10px; padding-left: 15px; padding-right: 15px; padding-top: 15px; width: 330px"> 

    <tr> 
	<td style="border: 0px; padding-bottom: 5px; padding-left: 0px; padding-right: 5px; padding-top:0px; text-align: right; vertical-align: middle"> 
        <span style="color: #333333; font-family: Open Sans, Arial, Helvetica, sans-serif; font-size: 12px;">Shipping & Taxes</span> 
    </td> 
	<td style="border: 0px; padding-bottom: 5px; padding-left: 5px; padding-right: 5px; padding-top:0px; vertical-align: middle"> 
        <input type="text" id="ship_zip" style="background-color: white; border-color: #999999; box-sizing: content-box; color: #999999; font-family: Open Sans; font-size: 13px; font-style: italic; height: 16px; margin: 0px; padding: 4px; width: 85px" value="Zip code"/>
    </td> 
    <td style="border: 0px; padding-bottom: 5px; padding-left: 5px; padding-right: 0px; padding-top:0px; vertical-align: middle"> 
        <input type="button" id="mk_cart_est_btn" value="Estimate" style="background-color: #F2F2F2; border-color: #999999; border-radius: 2px; border-width: 1px; color: #333333; font-family: Open Sans, Arial, Helvetica, sans-serif; font-size: 12px; font-weight: 600; height: 24px; margin: 0px; padding: 4px; width: 80px">    
    </td> 
    </tr> 

    <tr id="discount_code_row" style="display:none"> 
	<td style="border: 0px; padding-bottom: 5px; padding-left: 0px; padding-right: 5px; padding-top:5px; text-align: right; vertical-align: middle">
        <span id="discount_txt" style="color: #333333; font-family: Open Sans, Arial, Helvetica, sans-serif; font-size: 12px;">Discount</span> 
    	</td> 
	<td style="border: 0px; padding-bottom: 5px; padding-left: 5px; padding-right: 5px; padding-top:5px; vertical-align: middle"> 
        <input type="text" id="discount_code" style="background-color: white; border-color: #999999; box-sizing: content-box; color: #999999; font-family: Open Sans; font-size: 13px; font-style: italic; height: 16px; margin: 0px; padding: 4px; width: 85px" value="Coupon"/>
    </td> 
    <td style="border: 0px; padding-bottom: 5px; padding-left: 5px; padding-right: 0px; padding-top:5px; vertical-align: middle">
        <input type="button" id="mk_cart_apply_btn" value="Apply" style="background-color: #F2F2F2; border-color: #999999; border-radius: 2px; border-width: 1px; color: #333333; font-family: Open Sans, Arial, Helvetica, sans-serif; font-size: 12px; font-weight: 600; height: 24px; margin: 0px; padding: 4px; width: 80px">
    </td> 
    </tr> 

    <tr id="inprogress_indicator" style="display:none"> 
	<td colspan="3" style="border: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top:10px; text-align:center"> 
	    <img src="https://transactions.minkasu.com/images/spinning_wheel.gif"> 
	</td> 
    </tr> 

    <tr id="shipping_options_row" style="display:none"> 
	<td style="border: 0px; padding-bottom: 5px; padding-left: 0px; padding-right: 5px; padding-top:5px; text-align: right;"> 
        <span style="color: #333333; font-family: Open Sans, Arial, Helvetica, sans-serif; font-size: 12px;">Shipping</span> 
    	</td> 
    	<td id="shipping_options_cell" colspan="2" style="border: 0px; padding-bottom: 5px; padding-left: 5px; padding-right: 0px; padding-top:5px"> 
    	</td> 
    </tr> 
  
    <tr><td colspan="3" style="border: 0px; padding-bottom: 5px; padding-left: 0px; padding-right: 0px; padding-top:5px;"></td></tr> 

    <tr> 
    <td id="mk_checkout_td" colspan="3" style="border: 0px; border-top: 1px solid #DDDDDD; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top:10px;">
	<div id="minkasu_payment_div"> </div>
	<div class="buttons" style="height: 45px;">
	     <div class="right">
	     	  <input type="button" value="Checkout with Smart Phone (Minkasu)" id="button-mk-chkout" class="button" />
             </div>
	</div>
    </td> 
    </tr> 

    </table> 

    </td></tr>
    </table> 

    </div>

<?php else: ?>

    <div class="row">
    	<div class="col-sm-12" style="text-align:right" id="minkasu_payment_div"></div>
    </div>

    <div class="buttons" style="height: 45px;">
	<div class="right">
		<input type="button" value="Checkout with Smart Phone (Minkasu)" id="button-mk-chkout" class="button" />
	</div>
    </div>
 
<?php endif; ?>
